name: Check
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run ShellCheck
        uses: Azbagheri/shell-linter@v0.8.0
        with:
          path: "/github/workspace/autossh/run.sh"
